const sss = [
  {
    코드: 'GMP',
    구분: '한국',
    '공항명(영문)': '김포(GIMPO)',
  },
  {
    코드: 'ICN',
    구분: '한국',
    '공항명(영문)': '인천(INCHEON)',
  },
  {
    코드: 'CJU',
    구분: '한국',
    '공항명(영문)': '제주(JEJU)',
  },
  {
    코드: 'TAE',
    구분: '한국',
    '공항명(영문)': '대구(DAEGU)',
  },
  {
    코드: 'USN',
    구분: '한국',
    '공항명(영문)': '울산(ULSAN)',
  },
  {
    코드: 'CJJ',
    구분: '한국',
    '공항명(영문)': '청주(CHEONGJU)',
  },
  {
    코드: 'WJU',
    구분: '한국',
    '공항명(영문)': '원주(WONJU)',
  },
  {
    코드: 'YNY',
    구분: '한국',
    '공항명(영문)': '양양(YANGYANG)',
  },
  {
    코드: 'MWX',
    구분: '한국',
    '공항명(영문)': '무안(MUAN)',
  },
  {
    공항코드: 'KWJ',
    구분: '한국',
    '공항명(영문)': '광주(GWANGJU)',
  },
  {
    공항코드: 'RSU',
    구분: '한국',
    '공항명(영문)': '여수(YEOSU)',
  },
  {
    공항코드: 'KPO',
    구분: '한국',
    '공항명(영문)': '포항(POHANG)',
  },
  {
    공항코드: 'KUV',
    구분: '한국',
    '공항명(영문)': '군산(GUNSAN)',
  },
];

const JAPAN_AIRPORTS_DUMMY = [
  {
    titleEn: 'Aguni Airport',
    titleJa: '粟国空港',
    titleKo: '아구니 공항',
    iata: 'AGJ',
    icao: '',
    latitude: '26.588997644',
    longitude: '127.23749905',
    cityNameEn: 'Aguni',
    cityNameJa: '粟国',
    cityNameKo: '아구니',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '4550 Hama, Aguni, Shimajiri District, Okinawa 901-3701',
    link: 'https://www.pref.okinawa.jp',
  },
  {
    titleEn: 'Akita Airport',
    titleJa: '秋田空港',
    titleKo: '아키타 공항',
    iata: 'AXT',
    icao: 'RJSK',
    latitude: '39.609330896',
    longitude: '140.217832462',
    cityNameEn: 'Akita',
    cityNameJa: '	秋田',
    cityNameKo: '아키타',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '010-1211 Akita, Yuwatsubakigawa, Yamagomori-4 9',
    link: 'https://www.akita-airport.com',
  },
  {
    titleEn: 'Amakusa Airfield',
    titleJa: '天草空港',
    titleKo: '아마쿠사 공항',
    iata: 'AXJ',
    icao: 'RJDA',
    latitude: '32.80589',
    longitude: '130.69181',
    cityNameEn: 'Amakusa',
    cityNameJa: '天草',
    cityNameKo: '아마쿠사',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1 Chome-2080-5 Itsuwamachi Jogawara, Amakusa, Kumamoto 863-2114',
    link: 'https://www.pref.kumamoto.jp/soshiki/113/1369.html',
  },
  {
    titleEn: 'Amami Oshima Airport',
    titleJa: '奄美大島空港',
    titleKo: '아마미 공항',
    iata: 'ASJ',
    icao: 'RJKA',
    latitude: '28.4306',
    longitude: '129.713',
    cityNameEn: 'Amami',
    cityNameJa: '奄美大島',
    cityNameKo: '아마미',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '374-4 Kasaricho Oaza Wano, Amami, Kagoshima 894-0503',
    link: 'https://amami-airport.co.jp',
  },
  {
    titleEn: 'Aomori Airport',
    titleJa: '青森空港',
    titleKo: '아오모리 공항',
    iata: 'AOJ',
    icao: 'RJSA',
    latitude: '40.7333304',
    longitude: '140.686497254',
    cityNameEn: 'Aomori',
    cityNameJa: '青森',
    cityNameKo: '아오모리',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Kotani-1-5 Otani, Aomori, 030-0155',
    link: 'https://www.aomori-airport.co.jp',
  },
  {
    titleEn: 'Asahikawa Airport',
    titleJa: '旭川空港',
    titleKo: '아사히카와 공항',
    iata: 'AKJ',
    icao: 'RJEC',
    latitude: '43.66916399',
    longitude: '142.441831566',
    cityNameEn: 'Asahikawa',
    cityNameJa: '旭川',
    cityNameKo: '아사히카',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address:
      '2 Sen-16-98 Higashi, Higashikagura, Kamikawa District, Hokkaido 071-1562',
    link: 'https://www.aapb.co.jp',
  },
  {
    titleEn: 'Chofu Airport',
    titleJa: '調布空港',
    titleKo: '쵸후 공항',
    iata: '',
    icao: 'RJTF',
    latitude: '',
    longitude: '',
    cityNameEn: 'Chofu',
    cityNameJa: '調布',
    cityNameKo: '쵸후',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '290-3 Nishimachi, Chofu, Tokyo 182-0032',
    link: 'https://www.kouwan.metro.tokyo.lg.jp/rito/tmg-airport/chofu',
  },
  {
    titleEn: 'Fukuoka Airport',
    titleJa: '福岡空港',
    titleKo: '후쿠오카 공항',
    iata: 'FUK',
    icao: 'RJFF',
    latitude: '33.583997664',
    longitude: '130.450998196',
    cityNameEn: 'Fukuoka',
    cityNameJa: '福岡',
    cityNameKo: '후쿠오카',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '778-1 Shimousui, Hakata Ward, Fukuoka, 812-0003',
    link: 'https://www.fukuoka-airport.jp',
  },
  {
    titleEn: 'Fukue Airport',
    titleJa: '福江空港',
    titleKo: '고토 후쿠에 공항',
    iata: 'FUJ',
    icao: 'RJFE',
    latitude: '32.659664028',
    longitude: '128.826330028',
    cityNameEn: 'Fukue',
    cityNameJa: '福江',
    cityNameKo: '후쿠에',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '2183 Kamiozucho, Goto, Nagasaki 853-0042',
    link: 'https://www.fukuekuko.jp',
  },
  {
    titleEn: 'Hachijo Jima Airport',
    titleJa: '八丈島空港',
    titleKo: '하치조이지마 공항',
    iata: 'HAC',
    icao: 'RJTH',
    latitude: '33.108999564',
    longitude: '139.784830194',
    cityNameEn: 'Hachijo Jima',
    cityNameJa: '八丈島',
    cityNameKo: '하치조이지마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '2839-2 Okago, Hachijo, 八丈島 Tokyo 100-1401',
    link: 'https://hachijoapo.net',
  },
  {
    titleEn: 'Hakodate Airport',
    titleJa: '函館空港',
    titleKo: '하코다테 공항',
    iata: 'HKD',
    icao: 'RJCH',
    latitude: '41.768663592',
    longitude: '140.819830054',
    cityNameEn: 'Hakodate',
    cityNameJa: '函館',
    cityNameKo: '하코다테',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '511 Takamatsucho, Hakodate, Hokkaido 042-0952',
    link: 'https://airport.ne.jp',
  },
  {
    titleEn: 'Izumo Airport',
    titleJa: '出雲空港',
    titleKo: '이즈모 공항',
    iata: 'IZO',
    icao: 'RJOC',
    latitude: '35.408165034',
    longitude: '132.887329784',
    cityNameEn: 'Izumo',
    cityNameJa: '出雲',
    cityNameKo: '이즈모',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '2633-1 Hikawacho Okinosu, Izumo, Shimane 699-0502',
    link: 'https://www.izumo-airport.co.jp',
  },
  {
    titleEn: 'Hiroshima Airport',
    titleJa: '広島空港',
    titleKo: '히로시마 국제공항',
    iata: 'HIJ',
    icao: 'RJOA',
    latitude: '34.43499826',
    longitude: '132.91832966',
    cityNameEn: 'Hiroshima',
    cityNameJa: '広島',
    cityNameKo: '히로시마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '64-31 Hongocho Zennyuji, Mihara, Hiroshima 729-0416',
    link: 'https://www.hij.airport.jp',
  },
  {
    titleEn: 'Iki Airport',
    titleJa: '壱岐空港',
    titleKo: '이키 공항',
    iata: 'IKI',
    icao: 'RJDB',
    latitude: '33.742830362',
    longitude: '129.784830194',
    cityNameEn: 'Iki',
    cityNameJa: '壱岐',
    cityNameKo: '이키',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1725 Ishidacho Tsutsukihigashifure, Iki, Nagasaki 811-5203',
    link: 'https://www.orc-air.co.jp',
  },
  {
    titleEn: 'Shimojishima Airport',
    titleJa: 'みやこ下地島空港',
    titleKo: '시모지시마 공항',
    iata: 'SHI',
    icao: 'RORS',
    latitude: '24.80379',
    longitude: '125.30222',
    cityNameEn: 'Shimojishima',
    cityNameJa: 'みやこ下地島',
    cityNameKo: '시모지시마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Sawada-1727 Irabu, Miyakojima, Okinawa 906-0507',
    link: 'https://shimojishima.jp',
  },
  {
    titleEn: 'Ishigaki Airport',
    titleJa: '南ぬ島 石垣空港',
    titleKo: '이시가키 공항',
    iata: 'ISG',
    icao: 'ROIG',
    latitude: '24.340165306',
    longitude: '124.185499258',
    cityNameEn: 'Ishigaki',
    cityNameJa: '石垣空港',
    cityNameKo: '이시가키',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1960-104-1 Shiraho, Ishigaki, Okinawa 907-0242',
    link: 'https://www.ishigaki-airport.co.jp',
  },
  {
    titleEn: 'Oshima Airport',
    titleJa: '大島空港',
    titleKo: '오시마 공항',
    iata: 'OIM',
    icao: '',
    latitude: '34.77583023',
    longitude: '139.356165242',
    cityNameEn: 'Oshima',
    cityNameJa: '大島',
    cityNameKo: '오시마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Kitanoyama-270, Oshima, Tokyo 100-0101',
    link: 'https://www.kouwan.metro.tokyo.lg.jp/rito/tmg-airport/oshima',
  },
  {
    titleEn: 'Saga Airport',
    titleJa: '九州佐賀国際空港',
    titleKo: '사가 공항',
    iata: 'HSG',
    icao: 'RJFS',
    latitude: '',
    longitude: '',
    cityNameEn: 'Saga',
    cityNameJa: '佐賀',
    cityNameKo: '사가',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address:
      '840-2212 Saga, Kawasoemachi Oaza Inuido, 9476-187 旅客ターミナルビル',
    link: 'https://www.pref.saga.lg.jp',
  },
  {
    titleEn: 'Kikaiga Shima Airport',
    titleJa: '喜界空港',
    titleKo: '키카이 공항',
    iata: 'KKX',
    icao: 'RJKI',
    latitude: '28.319498722',
    longitude: '129.923496306',
    cityNameEn: 'Kikaiga',
    cityNameJa: '喜界',
    cityNameKo: '키카이',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '891-6203 Kagoshima, Oshima District, 喜界町中里字西牧201-9',
    link: 'https://www.homemate-research-airport.com',
  },
  {
    titleEn: 'Odate Noshiro Airport',
    titleJa: '大館能代空港',
    titleKo: '오다테 노시로 공항',
    iata: 'ONJ',
    icao: 'RJSR',
    latitude: '40.188499246',
    longitude: '140.369665188',
    cityNameEn: 'Odate',
    cityNameJa: '大館能代',
    cityNameKo: '오다테',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Karamushitai-21-144 Wakigami, Kitaakita, Akita 018-3454',
    link: 'https://onj-airterminal.com',
  },
  {
    titleEn: 'Kitakyushu Airport',
    titleJa: '北九州空港',
    titleKo: '고쿠라 공항',
    iata: 'KKJ',
    icao: 'RJFR',
    latitude: '33.840663304',
    longitude: '131.034333196',
    cityNameEn: 'Kitakyushu',
    cityNameJa: '北九州',
    cityNameKo: '고쿠라',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address:
      '6 Kuko Kitamachi, Kokuraminami Ward, Kitakyushu, Fukuoka 800-0306',
    link: 'https://www.kitakyu-air.jp',
  },
  {
    titleEn: 'Kitadaito Airport',
    titleJa: '北大東空港',
    titleKo: '기카 다이토 공항',
    iata: 'KTD',
    icao: '',
    latitude: '25.940162906',
    longitude: '131.322832042',
    cityNameEn: 'Kitadaito',
    cityNameJa: '北大東',
    cityNameKo: '기카 다이토',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '19-16 Minami, Kitadaito, Shimajiri District, Okinawa 901-3901',
    link: 'https://www.kitadaito.jp/access.html',
  },
  {
    titleEn: 'Osaka Kobe Airport',
    titleJa: '神戸空港',
    titleKo: '고베 공항',
    iata: 'UKB',
    icao: 'RJBE',
    latitude: '34.626330828',
    longitude: '135.220999116',
    cityNameEn: 'Kobe',
    cityNameJa: '神戸',
    cityNameKo: '고베',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1 Kobekuko, Chuo Ward, Kobe, Hyogo 650-0048',
    link: 'https://www.kairport.co.jp/',
  },
  {
    titleEn: 'Komatsu Airport',
    titleJa: '小松空港',
    titleKo: '코마쓰 공항',
    iata: 'KMQ',
    icao: 'RJNK',
    latitude: '36.389665108',
    longitude: '136.404498382',
    cityNameEn: 'Komatsu',
    cityNameJa: '小松',
    cityNameKo: '코마쓰',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '923-0993 Ishikawa, Komatsu, Ukiyanagimachi, Yo, ５０番地先',
    link: 'https://www.komatsuairport.jp',
  },
  {
    titleEn: 'Takamatsu Airport',
    titleJa: '高松空港',
    titleKo: '다카마쓰 공항',
    iata: 'TAK',
    icao: 'RJOT',
    latitude: '34.208499166',
    longitude: '134.009333296',
    cityNameEn: 'Takamatsu',
    cityNameJa: '高松',
    cityNameKo: '다카마쓰',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1312-7 Konanchooka, Takamatsu, Kagawa 761-1401',
    link: 'https://www.takamatsu-airport.com',
  },
  {
    titleEn: 'Kozushima Airport',
    titleJa: '神津島空港',
    titleKo: '코츄시마 공항',
    iata: '',
    icao: 'RJAZ',
    latitude: '34.186999252',
    longitude: '139.133499466',
    cityNameEn: 'Kozushima',
    cityNameJa: '神津島',
    cityNameKo: '코츄시마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Yakiyama, 字 Kozushima, Tokyo 100-0601',
    link: 'https://www.kouwan.metro.tokyo.lg.jp/rito/tmg-airport/kozushima/',
  },
  {
    titleEn: 'Kume-jima Airport',
    titleJa: '久米島空港',
    titleKo: '큐메지마 공항',
    iata: 'UEO',
    icao: 'ROKJ',
    latitude: '26.358165234',
    longitude: '126.7083305',
    cityNameEn: 'Kume-jima',
    cityNameJa: '久米島',
    cityNameKo: '큐메지마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address:
      '566-2 Kitahara, 字 Kumejima, Shimajiri District, Okinawa 901-3133',
    link: 'http://kumejima-airport.co.jp',
  },
  {
    titleEn: 'Kushiro Airport',
    titleJa: '釧路空港',
    titleKo: '쿠시로 공항',
    iata: 'KUH',
    icao: 'RJCK',
    latitude: '43.037833182',
    longitude: '144.18916591',
    cityNameEn: 'Kushiro',
    cityNameJa: '釧路',
    cityNameKo: '쿠시로',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '2 Tsuruoka, Kushiro, Hokkaido 084-0926',
    link: 'https://kushiro-airport.co.jp',
  },
  {
    titleEn: 'Kumamoto Airport',
    titleJa: '熊本空港',
    titleKo: '구마모토 공항',
    iata: 'KMJ',
    icao: 'RJFT',
    latitude: '32.835663324',
    longitude: '130.853163254',
    cityNameEn: 'Kumamoto',
    cityNameJa: '熊本',
    cityNameKo: '구마모토',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1802-2 Oyatsu, Mashiki, Kamimashiki District, Kumamoto 861-2204',
    link: 'https://www.kumamoto-airport.co.jp',
  },
  {
    titleEn: 'Iwami Airport',
    titleJa: '石見空港',
    titleKo: '이와미 공항',
    iata: 'IWJ',
    icao: 'RJOW',
    latitude: '34.67249731',
    longitude: '131.78749685',
    cityNameEn: 'Iwami',
    cityNameJa: '石見',
    cityNameKo: '이와미',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '597 Uchidacho, Masuda, Shimane 698-0051',
    link: 'https://hagiiwami.jp',
  },
  {
    titleEn: 'Matsumoto Airport',
    titleJa: '松本空港',
    titleKo: '마츠모토 공항',
    iata: 'MMJ',
    icao: 'RJAF',
    latitude: '36.166666',
    longitude: '137.920329652',
    cityNameEn: 'Matsumoto',
    cityNameJa: '松本',
    cityNameKo: '마츠모토',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '8909 Kukohigashi, Matsumoto, Nagano 390-1132',
    link: 'https://www.matsumoto-airport.co.jp',
  },
  {
    titleEn: 'Tokushima Awaodori Airport',
    titleJa: '徳島阿波おどり空港',
    titleKo: '토쿠시마 공항',
    iata: 'TKS',
    icao: 'RJOS',
    latitude: '34.126332828',
    longitude: '134.603997584',
    cityNameEn: 'Tokushima',
    cityNameJa: '徳島',
    cityNameKo: '토쿠시마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address:
      'Asahino-16-2 Toyohisa, Matsushige, Itano District, Tokushima 771-0213',
    link: 'https://www.tokushima-airport.co.jp/',
  },
  {
    titleEn: 'Matsuyama Airport',
    titleJa: '松山空港',
    titleKo: '마츠야마 공항',
    iata: 'MYJ',
    icao: 'RJOM',
    latitude: '33.822996708',
    longitude: '132.693163894',
    cityNameEn: 'Matsuyama',
    cityNameJa: '松山',
    cityNameKo: '마츠야마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '2731 Minamiyoshidamachi, Matsuyama, Ehime 791-8042',
    link: 'https://www.matsuyama-airport.co.jp',
  },
  {
    titleEn: 'Memanbetsu Airport',
    titleJa: '女満別空港',
    titleKo: '메만베쓰 공항',
    iata: 'MMB',
    icao: 'RJCM',
    latitude: '43.8749965',
    longitude: '144.158499366',
    cityNameEn: 'Memanbetsu',
    cityNameJa: '女満別',
    cityNameKo: '메만베쓰',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address:
      '201-3 Memanbetsuchuo, Ozora, Abashiri District, Hokkaido 099-2371',
    link: 'https://www.mmb-airport.co.jp',
  },
  {
    titleEn: 'Minami Daito Maridor Airport',
    titleJa: '南大東空港',
    titleKo: '마리도 공항',
    iata: 'MMD',
    icao: 'ROMD',
    latitude: '25.841329968',
    longitude: '131.258165634',
    cityNameEn: 'Maridor',
    cityNameJa: '南大東',
    cityNameKo: '마리도',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '258 Kyuto, Minamidaito, Shimajiri District, Okinawa 901-3803',
    link: 'https://www.airtrip.jp/airport/MMD',
  },
  {
    titleEn: 'Misawa Airport',
    titleJa: '三沢空港',
    titleKo: '미사와 공항',
    iata: 'MSJ',
    icao: 'RJSM',
    latitude: '40.703163854',
    longitude: '141.369831854',
    cityNameEn: 'Misawa',
    cityNameJa: '三沢',
    cityNameKo: '미사와',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Shitasawa-83-198 Misawa, Aomori 033-0022',
    link: 'https://misawa-airport.co.jp',
  },
  {
    titleEn: 'Miyake Jima Airport',
    titleJa: '三宅島空港',
    titleKo: '미아케지마 공항',
    iata: 'MYE',
    icao: '',
    latitude: '34.07083305',
    longitude: '139.556164442',
    cityNameEn: 'Miyake Jima',
    cityNameJa: '三宅島',
    cityNameKo: '미아케지마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1378 Tsubota, 三宅村 三宅島 Tokyo 100-1211',
    link: 'https://www.homemate-research-airport.com/dtl/00000000000000204322',
  },
  {
    titleEn: 'Miyako Hirara Airport',
    titleJa: '宮古空港',
    titleKo: '히라라 공항',
    iata: 'MMY',
    icao: 'ROMY',
    latitude: '24.776330228',
    longitude: '125.290332172',
    cityNameEn: 'Hirara',
    cityNameJa: '宮古',
    cityNameKo: '히라라',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Shimozato-1657-128 Hirara, Miyakojima, Okinawa 906-0013',
    link: 'https://miyakoap.co.jp',
  },
  {
    titleEn: 'Miyazaki Airport',
    titleJa: '宮崎空港',
    titleKo: '미야자키 공항',
    iata: 'KMI',
    icao: 'RJFM',
    latitude: '31.872996508',
    longitude: '131.44249823',
    cityNameEn: 'Miyazaki',
    cityNameJa: '宮崎',
    cityNameKo: '미야자키',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Akae, Miyazaki, 880-0912',
    link: 'https://www.miyazaki-airport.co.jp',
  },
  {
    titleEn: 'Kagoshima Airport',
    titleJa: '鹿児島空港',
    titleKo: '가고시마 공항',
    iata: 'KOJ',
    icao: 'RJFK',
    latitude: '31.801996792',
    longitude: '130.716830466',
    cityNameEn: 'Kagoshima',
    cityNameJa: '鹿児島',
    cityNameKo: '가고시마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '822 Mizobechofumoto, Kirishima, Kagoshima 899-6404',
    link: 'https://www.koj-ab.co.jp',
  },
  {
    titleEn: 'Monbetsu Airport',
    titleJa: '紋別空港',
    titleKo: '몬베쓰 공항',
    iata: 'MBE',
    icao: 'RJEB',
    latitude: '44.3525',
    longitude: '143.3525',
    cityNameEn: 'Monbetsu',
    cityNameJa: '紋別',
    cityNameKo: '몬베쓰',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '19-3 Komukai, Mombetsu, Hokkaido 099-6132',
    link: 'https://www.ok-m.jp',
  },
  {
    titleEn: 'Hanamaki Airport',
    titleJa: 'いわて花巻空港',
    titleKo: '하나마키 공항',
    iata: 'HNA',
    icao: 'RJSI',
    latitude: '39.38333',
    longitude: '141.11667',
    cityNameEn: 'Hanamaki',
    cityNameJa: 'いわて花巻',
    cityNameKo: '하나마키',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '025-0003 Iwate, Hanamaki, Higashimiyanome, Dai 2 Chiwari, 53番地',
    link: 'https://www.hna-terminal.co.jp',
  },
  {
    titleEn: 'Oita Airport',
    titleJa: '大分空港',
    titleKo: '오이타 공항',
    iata: 'OIT',
    icao: 'RJFO',
    latitude: '33.474331436',
    longitude: '131.735663724',
    cityNameEn: 'Oita',
    cityNameJa: '大分',
    cityNameKo: '오이타',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '13 Akimachi Shimobaru, Kunisaki, Oita 873-0231',
    link: 'https://www.oita-airport.jp',
  },
  {
    titleEn: 'Nagoya Chubu Centrair International Airport',
    titleJa: '中部国際空港',
    titleKo: '주부 센트에어 국제공항',
    iata: 'NGO',
    icao: 'RJGG',
    latitude: '34.85499658',
    longitude: '136.803163454',
    cityNameEn: 'Chubu',
    cityNameJa: '中部',
    cityNameKo: '주부',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '479-0881 Aichi, Tokoname, Centrair, 1 Chome, 1番地',
    link: 'https://www.centrair.jp/index.html',
  },
  {
    titleEn: 'Nagoya Komaki Airport',
    titleJa: '県営名古屋空港',
    titleKo: '코마키 공항',
    iata: 'NKM',
    icao: 'RJNA',
    latitude: '35.252998988',
    longitude: '136.921329648',
    cityNameEn: 'Nagoya',
    cityNameJa: '名古屋',
    cityNameKo: '나고야',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Toyoyama, Nishikasugai District, Aichi 480-0202',
    link: 'https://nagoya-airport.jp',
  },
  {
    titleEn: 'Nakashibetsu Airport',
    titleJa: '中標津空港',
    titleKo: '나가시베쓰 공항',
    iata: 'SHB',
    icao: 'RJCN',
    latitude: '43.573164374',
    longitude: '144.955996176',
    cityNameEn: 'Nakashibetsu',
    cityNameJa: '中標津',
    cityNameKo: '나가시베쓰',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address:
      '16-9 Kitanaka, Nakashibetsu, Shibetsu District, Hokkaido 086-1145',
    link: 'https://www.nakashibetsu-airport.jp',
  },
  {
    titleEn: 'Kochi Ryoma Airport',
    titleJa: '高知空港',
    titleKo: '고치 공항',
    iata: 'KCZ',
    icao: 'RJOK',
    latitude: '33.540997836',
    longitude: '133.66833066',
    cityNameEn: 'Kochi',
    cityNameJa: '高知',
    cityNameKo: '고치',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '5 8 Hisaeda, Nankoku, Kochi 783-0096',
    link: 'https://www.kochiap.co.jp',
  },
  {
    titleEn: 'Sendai Airport',
    titleJa: '仙台空港',
    titleKo: '센다이 공항',
    iata: 'SDJ',
    icao: 'RJSS',
    latitude: '38.137166118',
    longitude: '140.916829666',
    cityNameEn: 'Sendai',
    cityNameJa: '仙台',
    cityNameKo: '센다이',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Minamihara-無番地 Shimomasuda, Natori, Miyagi 989-2401',
    link: 'https://www.sendai-airport.co.jp',
  },
  {
    titleEn: 'Niigata Airport',
    titleJa: '新潟空港',
    titleKo: '니가타 공항',
    iata: 'KIJ',
    icao: 'RJSN',
    latitude: '37.953496186',
    longitude: '139.106999572',
    cityNameEn: 'Niigata',
    cityNameJa: '新潟',
    cityNameKo: '니가타',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '3710 Matsuhamacho, Higashi Ward, Niigata, 950-0001',
    link: 'https://www.niigata-airport.gr.jp',
  },
  {
    titleEn: 'Obihiro Airport',
    titleJa: '帯広空港',
    titleKo: '오비히로 공항',
    iata: 'OBO',
    icao: 'RJCB',
    latitude: '42.7333304',
    longitude: '143.216999132',
    cityNameEn: 'Obihiro',
    cityNameJa: '帯広',
    cityNameKo: '오비히로',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Nishi 9 Sen-中８-4 1 Izumicho, Obihiro, Hokkaido 089-1245',
    link: 'https://obihiro-airport.com',
  },
  {
    titleEn: 'Ibaraki Airport',
    titleJa: '茨城空港',
    titleKo: '이바라키 공항',
    iata: 'IBR',
    icao: 'RJAH',
    latitude: '',
    longitude: '',
    cityNameEn: 'Ibaraki',
    cityNameJa: '茨城',
    cityNameKo: '이바라키',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1601-55 Yozawa, Omitama, Ibaraki 311-3416',
    link: 'https://www.ibaraki-airport.net',
  },
  {
    titleEn: 'Okayama Airport',
    titleJa: '岡山空港',
    titleKo: '오카야마 공항',
    iata: 'OKJ',
    icao: 'RJOB',
    latitude: '33.822996708',
    longitude: '132.693163894',
    cityNameEn: 'Okayama',
    cityNameJa: '岡山',
    cityNameKo: '오카야마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1277 Nichioji, Kita Ward, Okayama, 701-1131',
    link: 'https://www.okayama-airport.org',
  },
  {
    titleEn: 'Okinawa Naha Airport',
    titleJa: '那覇空港',
    titleKo: '나하 공항',
    iata: 'OKA',
    icao: 'ROAH',
    latitude: '26.19083257',
    longitude: '127.64083077',
    cityNameEn: 'Naha',
    cityNameJa: '那覇',
    cityNameKo: '나하',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '150 Kagamizu, Naha, Okinawa 901-0142',
    link: 'https://www.naha-airport.co.jp',
  },
  {
    titleEn: 'Oki Island Airport',
    titleJa: '隠岐空港',
    titleKo: '오키 공항',
    iata: 'OKI',
    icao: 'RJNO',
    latitude: '',
    longitude: '',
    cityNameEn: 'Oki',
    cityNameJa: '隠岐',
    cityNameKo: '오키',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1889-12 Misakimachi, Okinoshima, Oki District, Shimane 685-0021',
    link: 'http://www.oki-airport.jp',
  },
  {
    titleEn: 'Okushiri Airport',
    titleJa: '奥尻空港',
    titleKo: '오쿠시리 공항',
    iata: 'OIR',
    icao: 'RJEO',
    latitude: '',
    longitude: '',
    cityNameEn: 'Okushiri',
    cityNameJa: '奥尻',
    cityNameKo: '오쿠시리',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Yoneoka-185-2, Okushiri, Okushiri District, Hokkaido 043-1524',
    link: 'https://www.town.okushiri.lg.jp/hotnews/detail/00001538.html',
  },
  {
    titleEn: 'Nagasaki Airport',
    titleJa: '長崎空港',
    titleKo: '나가사키 공항',
    iata: 'NGS',
    icao: 'RJFU',
    latitude: '32.916829666',
    longitude: '129.908163034',
    cityNameEn: 'Nagasaki',
    cityNameJa: '長崎',
    cityNameKo: '나가사키',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '593 Mishimamachi, Ōmura, Nagasaki 856-0816',
    link: 'https://nagasaki-airport.jp',
  },
  {
    titleEn: 'Osaka Itami Airport',
    titleJa: '大阪国際空港',
    titleKo: '이타미 공항',
    iata: 'ITM',
    icao: 'RJOO',
    latitude: '34.783996864',
    longitude: '135.436831586',
    cityNameEn: 'Itami',
    cityNameJa: '大阪',
    cityNameKo: '이타미',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '3 Chome-555 Hotarugaike Nishimachi, Toyonaka, Osaka 560-0036',
    link: 'https://www.osaka-airport.co.jp',
  },
  {
    titleEn: 'Osaka Kansai International Airport',
    titleJa: '関西国際空港',
    titleKo: '간사이 국제공항',
    iata: 'KIX',
    icao: 'RJBB',
    latitude: '34.433831598',
    longitude: '135.226332428',
    cityNameEn: 'Kansai',
    cityNameJa: '関西',
    cityNameKo: '간사이',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1 Senshukukokita, Izumisano, Osaka 549-0001',
    link: 'https://www.kansai-airport.or.jp',
  },
  {
    titleEn: 'Rishiri Airport',
    titleJa: '利尻空港',
    titleKo: '리시리 공항',
    iata: 'RIS',
    icao: 'RJER',
    latitude: '',
    longitude: '',
    cityNameEn: 'Rishiri',
    cityNameJa: '利尻',
    cityNameKo: '리시리/',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address:
      'Motodomari-１１４３番地 Oshidomari, Rishirifuji, Rishiri District, Hokkaido 097-0101',
    link: 'https://www.town.rishirifuji.hokkaido.jp/rishirifuji/1184.htm',
  },
  {
    titleEn: 'Sado Airport',
    titleJa: '佐渡空港',
    titleKo: '사도 공항',
    iata: 'SDS',
    icao: 'RJSD',
    latitude: '38.05666644',
    longitude: '138.408498366',
    cityNameEn: 'Sado',
    cityNameJa: '佐渡',
    cityNameKo: '사도',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1814-3 Akitsu, Sado, Niigata 952-0021',
    link: 'https://www.pref.niigata.lg.jp/sec/sado_seibi/1204045245988.html',
  },
  {
    titleEn: 'Shonai Airport',
    titleJa: '庄内空港',
    titleKo: '쇼나이 공항',
    iata: 'SYO',
    icao: 'RJSY',
    latitude: '38.807330104',
    longitude: '139.785663524',
    cityNameEn: 'Shonai',
    cityNameJa: '庄内',
    cityNameKo: '쇼나이',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '998-0112 Yamagata, Sakata, 市浜中字村東30-3',
    link: 'https://www.shonai-airport.co.jp',
  },
  {
    titleEn: 'Sapporo Chitose Airport',
    titleJa: '新千歳空港',
    titleKo: '치토세 공항',
    iata: 'CTS',
    icao: 'RJCC',
    latitude: '42.771830246',
    longitude: '141.688830578',
    cityNameEn: 'Chitose',
    cityNameJa: '千歳',
    cityNameKo: '치토세',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Bibi, Chitose, Hokkaido 066-0012',
    link: 'https://www.new-chitose-airport.jp/ja',
  },
  {
    titleEn: 'Sapporo Okadama Airport',
    titleJa: '札幌丘珠空港',
    titleKo: '오카다마 공항',
    iata: 'OKD',
    icao: 'RJCO',
    latitude: '43.117166198',
    longitude: '141.375498498',
    cityNameEn: 'Okadama',
    cityNameJa: '丘珠',
    cityNameKo: '오카다마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Okadamacho, Higashi Ward, Sapporo, Hokkaido 007-0880',
    link: 'https://www.okadama-airport.co.jp',
  },
  {
    titleEn: 'Shirahama Airport',
    titleJa: '南紀白浜空港',
    titleKo: '난키 시라하마 공항',
    iata: 'SHM',
    icao: 'RJBD',
    latitude: '33.657330704',
    longitude: '135.358665232',
    cityNameEn: 'Shirahama',
    cityNameJa: '白浜',
    cityNameKo: '시라하마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1622-125 Saino, Shirahama, Nishimuro District, Wakayama 649-2211',
    link: 'http://shirahama-airport.jp',
  },
  {
    titleEn: 'Mount Fuji Shizuoka Airport',
    titleJa: '富士山静岡空港',
    titleKo: '시즈오카 공항',
    iata: 'FSZ',
    icao: 'RJNS',
    latitude: '34.790996836',
    longitude: '138.186999252',
    cityNameEn: 'Shizuoka',
    cityNameJa: '静岡',
    cityNameKo: '시즈오카',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '3336-4 Sakaguchi, Makinohara, Shizuoka 421-0411',
    link: 'https://www.mtfuji-shizuokaairport.jp',
  },
  {
    titleEn: 'Toyooka Tajima Airport',
    titleJa: 'コウノトリ但馬空港',
    titleKo: '타지마 공항',
    iata: 'TJH',
    icao: 'RJBT',
    latitude: '35.507664636',
    longitude: '134.785496858',
    cityNameEn: 'Tajima',
    cityNameJa: '但馬',
    cityNameKo: '타지마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '668-0081 Hyogo, Toyooka, Iwai, 字河谷1598-34',
    link: 'https://www.tajima-airport.jp',
  },
  {
    titleEn: 'Fukushima Airport',
    titleJa: '福島空港',
    titleKo: '후쿠시마 공항',
    iata: 'FKS',
    icao: 'RJSF',
    latitude: '37.223165774',
    longitude: '140.423498306',
    cityNameEn: 'Fukushima',
    cityNameJa: '福島',
    cityNameKo: '후쿠시마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address:
      'Habakida-21 Kitasugama, Tamakawa, Ishikawa District, Fukushima 963-6304',
    link: 'https://fks-ab.co.jp',
  },
  {
    titleEn: 'Tanegashima Airport',
    titleJa: '種子島空港',
    titleKo: '다네가시마  공항',
    iata: 'TNE',
    icao: 'RJFG',
    latitude: '30.602997588',
    longitude: '130.98832938',
    cityNameEn: 'Tanegashima',
    cityNameJa: '種子島',
    cityNameKo: '다네가시마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '2692-64 Masuda, Nakatane, Kumage District, Kagoshima 891-3603',
    link: 'https://www.pref.kagoshima.jp/ah09/infra/port/kuko/tanegashima-.html',
  },
  {
    titleEn: 'Tarama Island Airport',
    titleJa: '多良間空港',
    titleKo: '타라마 공항',
    iata: 'TRA',
    icao: 'RORT',
    latitude: '24.652330724',
    longitude: '124.671830646',
    cityNameEn: 'Tarama',
    cityNameJa: '多良間',
    cityNameKo: '타라마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '2351-7 Nakasuji, Tarama, Miyako District, Okinawa 906-0602',
    link: 'https://www.vill.tarama.okinawa.jp/about/access/hikouki',
  },
  {
    titleEn: 'Tokunoshima Airport',
    titleJa: '徳之島空港',
    titleKo: '도쿠노시마 공항',
    iata: 'TKN',
    icao: 'RJKN',
    latitude: '27.835163326',
    longitude: '128.875496498',
    cityNameEn: 'Tokunoshima',
    cityNameJa: '徳之島',
    cityNameKo: '도쿠노시마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1-1 Asama, Amagi, Oshima District, Kagoshima 891-7605',
    link: 'https://www.pref.kagoshima.jp/ah09/infra/port/kuko/tokunoshima.html',
  },
  {
    titleEn: 'Tokyo Haneda Airport',
    titleJa: '羽田空港',
    titleKo: '하네다공항',
    iata: 'HND',
    icao: 'RJTT',
    latitude: '35.5499919',
    longitude: '139.7864664',
    cityNameEn: 'Ota',
    cityNameJa: '大田',
    cityNameKo: '오타',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Hanedakuko, Ota City, Tokyo 144-0041',
    link: 'https://tokyo-haneda.com',
  },
  {
    titleEn: 'Tokyo Narita Airport',
    titleJa: '成田国際空港',
    titleKo: '나리타 공항',
    iata: 'NRT',
    icao: 'RJAA',
    latitude: '35.78333',
    longitude: '140.31667',
    cityNameEn: 'Narita',
    cityNameJa: '成田',
    cityNameKo: '나리타',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1-1 Furugome, Narita, Chiba 282-0004',
    link: 'https://www.narita-airport.jp/en',
  },
  {
    titleEn: 'Tottori Sand Dunes Conan Airport',
    titleJa: '鳥取空港',
    titleKo: '돗토리 공항',
    iata: 'TTJ',
    icao: 'RJOR',
    latitude: '35.524664568',
    longitude: '134.15749937',
    cityNameEn: 'Tottori',
    cityNameJa: '鳥取',
    cityNameKo: '돗토리',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '4 Chome-110-5 Koyamachonishi, Tottori, 680-0947',
    link: 'https://www.ttj-ap-bld.co.jp',
  },
  {
    titleEn: 'Toyama Airport',
    titleJa: '富山空港',
    titleKo: '토하마 공항',
    iata: 'TOY',
    icao: 'RJNT',
    latitude: '33.822996708',
    longitude: '132.693163894',
    cityNameEn: 'Toyama',
    cityNameJa: '富山',
    cityNameKo: '토하마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '0 Akigashima, Toyama, 939-8252',
    link: 'https://www.toyama-airport.co.jp/',
  },
  {
    titleEn: 'Tsushima Airport',
    titleJa: '対馬空港',
    titleKo: '쓰시마 공항',
    iata: 'TSJ',
    icao: 'RJDT',
    latitude: '34.416665',
    longitude: '129.333332',
    cityNameEn: 'Tsushima',
    cityNameJa: '対馬',
    cityNameKo: '쓰시마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '440 Mitsushimamachi Kechi, Tsushima, Nagasaki 817-0322',
    link: 'https://tsushima-airport.co.jp',
  },
  {
    titleEn: 'Ube Airport',
    titleJa: '山口宇部空港',
    titleKo: '야마구치 우베 공항',
    iata: 'UBJ',
    icao: 'RJDC',
    latitude: '33.924662968',
    longitude: '131.273832238',
    cityNameEn: 'Ube',
    cityNameJa: '宇部',
    cityNameKo: '우베',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '625 Okiube, Ube, Yamaguchi 755-0001',
    link: 'https://www.yamaguchiube-airport.jp',
  },
  {
    titleEn: 'Okinoerabu Airport',
    titleJa: '沖永良部空港',
    titleKo: '오키노에라부 공항',
    iata: 'OKE',
    icao: 'RJKB',
    latitude: '27.425664964',
    longitude: '128.70333052',
    cityNameEn: 'Okinoerabu',
    cityNameJa: '沖永良部',
    cityNameKo: '오키노에라부',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1732-2 Kunigami, Wadomari, Oshima District, Kagoshima 891-9101',
    link: 'https://www.pref.kagoshima.jp/ah09/infra/port/kuko/okinoerabu.html',
  },
  {
    titleEn: 'Wajima Noto Airport',
    titleJa: '能登空港',
    titleKo: '노토 공항',
    iata: 'NTQ',
    icao: 'RJNW',
    latitude: '37.289332176',
    longitude: '136.957329504',
    cityNameEn: 'Noto',
    cityNameJa: '能登',
    cityNameKo: '노토',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Sue-10-11-1 Miimachi, Wajima, Ishikawa 929-2372',
    link: 'https://www.noto-airport.jp',
  },
  {
    titleEn: 'Wakkanai Hokkaido Airport',
    titleJa: '稚内空港',
    titleKo: '왓카나이 공항',
    iata: 'WKJ',
    icao: 'RJCW',
    latitude: '45.40944',
    longitude: '141.67389',
    cityNameEn: 'Wakkanai',
    cityNameJa: '稚内',
    cityNameKo: '와카나이',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Koetoi-6744 Koetoimura, Wakkanai, Hokkaido 098-6643',
    link: 'https://www.wkj-airport.jp',
  },
  {
    titleEn: 'Iwakuni Kintaikyo Airport',
    titleJa: '岩国錦帯橋空港',
    titleKo: '이와쿠니 긴타이쿄 공항',
    iata: 'IWK',
    icao: 'RJOI',
    latitude: '34.16297',
    longitude: '132.22',
    cityNameEn: 'Iwakuni',
    cityNameJa: '岩国',
    cityNameKo: '이와쿠니',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '3 Chome-15-1 Asahimachi, Iwakuni, Yamaguchi 740-0024',
    link: 'https://www.iwakuni-airport.jp',
  },
  {
    titleEn: 'Yakushima Airport',
    titleJa: '屋久島空港',
    titleKo: '야쿠시마 공항',
    iata: 'KUM',
    icao: 'RJFC',
    latitude: '30.384665128',
    longitude: '130.655497378',
    cityNameEn: 'Yakushima',
    cityNameJa: '屋久島',
    cityNameKo: '야쿠시마',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '501 Koseda, Yakushima, Kumage District, Kagoshima 891-4207',
    link: 'https://www.pref.kagoshima.jp/ah09/infra/port/kuko/yakushima.html',
  },
  {
    titleEn: 'Yamagata Junmachi Airport',
    titleJa: '山形空港',
    titleKo: '야마가타 공항',
    iata: 'GAJ',
    icao: 'RJSC',
    latitude: '38.407165038',
    longitude: '140.369331856',
    cityNameEn: 'Yamagata',
    cityNameJa: '山形',
    cityNameKo: '야마가타',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '999-3776 Yamagata, Higashine, Hanyu, 柏原新林3008',
    link: 'https://www.yamagata-airport.co.jp',
  },
  {
    titleEn: 'Osaka Yao Airport',
    titleJa: '八尾空港',
    titleKo: '야오 공항',
    iata: '',
    icao: 'RJOY',
    latitude: '34.591330968',
    longitude: '135.600330932',
    cityNameEn: 'Yao',
    cityNameJa: '八尾',
    cityNameKo: '야오',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: ' Chome-12 Airport, Yao, Osaka 581-0043',
    link: 'http://www.yaomania.jp/data/InfoDetail.asp?id=1884',
  },
  {
    titleEn: 'Yonago Miho Airport',
    titleJa: '米子空港',
    titleKo: '요나고 공항',
    iata: 'YGJ',
    icao: 'RJOH',
    latitude: '35.5023',
    longitude: '133.2475',
    cityNameEn: 'Miho',
    cityNameJa: '米子',
    cityNameKo: '요나고',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '1634 Sainokamicho, Sakaiminato, Tottori 684-0055',
    link: 'https://www.yonago-air.com',
  },
  {
    titleEn: 'Yonaguni Airport',
    titleJa: '与那国空港',
    titleKo: '요나구미 공항',
    iata: 'OGN',
    icao: 'ROYN',
    latitude: '24.467164798',
    longitude: '122.974496102',
    cityNameEn: 'Yonaguni',
    cityNameJa: '与那国',
    cityNameKo: '요나구미',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '4350 Yonaguni, Yaeyama District, Okinawa 907-1801',
    link: 'https://welcome-yonaguni.jp/guide/area/%E7%A9%BA%E6%B8%AF',
  },
  {
    titleEn: 'Yoron Airport',
    titleJa: '与論空港',
    titleKo: '요룬 공항',
    iata: 'RNJ',
    icao: 'RORY',
    latitude: '27.039666508',
    longitude: '128.400998396',
    cityNameEn: 'Yoron',
    cityNameJa: '与論',
    cityNameKo: '요룬',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '57 Ritcho, Yoron, Oshima District, Kagoshima 891-9302',
    link: 'https://www.pref.kagoshima.jp/ah09/infra/port/kuko/yoron.html',
  },
  {
    titleEn: 'Okinawa Kadena Air Force Base',
    titleJa: '嘉手納飛行場',
    titleKo: '오키나와 가데나 공군 기지',
    iata: 'DNA',
    icao: '',
    latitude: '26.350998596',
    longitude: '127.76833026',
    cityNameEn: 'Kadena',
    cityNameJa: '嘉手納',
    cityNameKo: '가데나',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: '04-0201 Okinawa, Nakagami District, Kadena, Kudoku, Unnamed Road',
    link: 'https://www.pref.okinawa.jp/heiwakichi/kichi/1017294/1017314.html',
  },
  {
    titleEn: 'Iwoto (Iwo Jima)',
    titleJa: '硫黄島航空基地',
    titleKo: '이오토 (이오지마)',
    iata: 'IWO',
    icao: 'RJAW',
    latitude: '30.787830182',
    longitude: '130.290998836',
    cityNameEn: 'Iwoto',
    cityNameJa: '硫黄島航空基地',
    cityNameKo: '',
    countryNameEn: 'japan',
    countryNameJa: '日本',
    countryNameKo: '일본',
    countryCode: 'JP',
    address: 'Iōjima, Ogasawara, Tokyo 100-2100',
    link: 'https://www.vill.ogasawara.tokyo.jp/ioutou_index/ioutou_development',
  },
];
