import { Prisma } from '@prisma/client';

export const carriersDummy: Prisma.AirlineCreateInput[] = [
  {
    titleEn: 'Jeju Air',
    titleJa: '濟州航空',
    titleKo: '제주항공',
    iata: '7C',
    icao: 'JJA',
    link: 'https://www.jejuair.net/ko/main/base/index.do',
    nationality: 'korea',
    imgTitle: 'Jeju_Air_Logo.png',
    seviceType: 'lcc',
  },
  {
    titleEn: 'tway Air',
    titleJa: 'ティーウェイ航空',
    titleKo: '티웨이항공',
    iata: 'TW',
    icao: 'TWB',
    link: 'http://www.twayair.com/',
    nationality: 'korea',
    imgTitle: 'Tway_Air_logo.png',
    seviceType: 'lcc',
  },
  {
    titleEn: 'Air Seoul',
    titleJa: 'エアソウル',
    titleKo: '에어서울',
    iata: 'RS',
    icao: 'ASV',
    link: 'https://flyairseoul.com/CW/ko/main.do',
    nationality: 'korea',
    imgTitle: 'Air_Seoul.png',
    seviceType: 'lcc',
  },
  {
    titleEn: 'Eastar Jet',
    titleJa: 'イースター航空',
    titleKo: '이스타항공',
    iata: 'ZE',
    icao: 'ESR',
    link: 'http://www.eastarjet.com/',
    nationality: 'korea',
    imgTitle: 'Eastar_Jet_Logo.png',
    seviceType: 'lcc',
  },
  {
    titleEn: 'Korean Air',
    titleJa: '大韓航空',
    titleKo: '대한항공',
    iata: 'KE',
    icao: 'KAL',
    link: 'https://www.koreanair.com/',
    nationality: 'korea',
    imgTitle: 'Korean_Air_Logo.png',
    seviceType: 'fsc',
  },
  {
    titleEn: 'AIR BUSAN',
    titleJa: '釜山航空',
    titleKo: '에어부산',
    iata: 'BX',
    icao: 'ABL',
    link: 'http://www.airbusan.com/',
    nationality: 'korea',
    imgTitle: 'Air_Busan_logo.png',
    seviceType: 'lcc',
  },
  {
    titleEn: 'Asiana Airlines',
    titleJa: 'アシアナ航空',
    titleKo: '아시아나항공',
    iata: 'OZ',
    icao: 'AAR',
    link: 'https://flyasiana.com/',
    nationality: 'korea',
    imgTitle: 'Asiana_Airlines-Logo.png',
    seviceType: 'fsc',
  },
  {
    titleEn: 'Jin Air',
    titleJa: 'ジンエア航空',
    titleKo: '진에어',
    iata: 'LJ',
    icao: 'JNA',
    link: 'https://www.jinair.com/',
    nationality: 'korea',
    imgTitle: 'Jin_Air_logo.png',
    seviceType: 'lcc',
  },
  {
    titleEn: 'Aero K',
    titleJa: 'エアロケイ航空',
    titleKo: '에어로케이항공',
    iata: 'RF',
    icao: 'EOK',
    link: 'https://www.aerok.com/',
    nationality: 'korea',
    imgTitle: 'Aero_K_logo.png',
    seviceType: 'lcc',
  },
  {
    titleEn: 'Japan Airlines',
    titleJa: '日本航空',
    titleKo: '일본항공',
    iata: 'JL',
    icao: 'JAL',
    link: 'http://www.jal.co.jp/',
    nationality: 'japan',
    imgTitle: 'japan-airlines.png',
    seviceType: 'fsc',
  },
  {
    titleEn: 'All Nippon Airways',
    titleJa: '全日本空輸',
    titleKo: '전일본공수',
    iata: 'NH',
    icao: 'ANA',
    link: 'https://www.ana.co.jp/',
    nationality: 'japan',
    imgTitle: 'All_Nippon_Airways_Logo.png',
    seviceType: 'fsc',
  },
  {
    titleEn: 'Air Japan',
    titleJa: 'エアージャパン',
    titleKo: '에어재팬',
    iata: 'NQ',
    icao: 'AJX',
    link: 'https://www.flyairjapan.com/',
    nationality: 'japan',
    imgTitle: 'air-japan.png',
    seviceType: 'fsc',
  },
  {
    titleEn: 'Peach Aviation',
    titleJa: 'ピーチ アビエーション',
    titleKo: '피치 항공',
    iata: 'MM',
    icao: 'APJ',
    link: 'http://www.flypeach.com/kr2/home.aspx',
    nationality: 'japan',
    imgTitle: 'Peach_Aviation_Logo.png',
    seviceType: 'lcc',
  },
  {
    titleEn: 'Ethiopian Airlines',
    titleJa: 'エチオピア航空',
    titleKo: '에티오피아 항공',
    iata: 'ET',
    icao: 'ETH',
    link: 'http://www.ethiopianairlines.com/',
    nationality: 'norway',
    imgTitle: 'ethiopian-airlines-logo.png',
    seviceType: 'fsc',
  },
  {
    titleEn: 'ZIPAIR Tokyo',
    titleJa: 'エチオピア航空',
    titleKo: '집에어 도쿄',
    iata: 'ZG',
    icao: 'TZP',
    link: 'https://www.zipair.net/',
    nationality: 'norway',
    imgTitle: 'ZIPAIR_Tokyo_logo.png',
    seviceType: 'lcc',
  },
  {
    titleEn: 'Air Premia',
    titleJa: 'エアプレミア',
    titleKo: '에어프레미아',
    iata: 'YP',
    icao: 'APZ',
    link: 'https://airpremia.com/',
    nationality: 'korea',
    imgTitle: 'Air_PREMIA_Logo.png',
    seviceType: 'hsc',
  },
];
